### PR TITLE
Fix errors in hivemind.p2p and hivemind.compression

### PR DESCRIPTION
**Pull request by borzunov**
This PR:

1. Fixes warnings in hivemind.p2p destructors:

    ```python
    Exception ignored in: <function P2P.__del__ at 0x7fbec8be5f70>
    Traceback (most recent call last):
      File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/p2p/p2p_daemon.py", line 636, in __del__
        self._terminate()
      File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/p2p/p2p_daemon.py", line 657, in _terminate
        self._child.terminate()
      File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/asyncio/subprocess.py", line 141, in terminate
        self._transport.terminate()
      File "uvloop/handles/process.pyx", line 636, in uvloop.loop.UVProcessTransport.terminate
      File "uvloop/handles/process.pyx", line 378, in uvloop.loop.UVProcessTransport._check_proc
    ProcessLookupError:
    Exception ignored in: <function Client.__del__ at 0x7fbec8bd7a60>
    Traceback (most recent call last):
      File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/p2p/p2p_daemon_bindings/p2pclient.py", line 53, in __del__
        self.close()
      File "/home/jheuristic/anaconda3/envs/py38_petals_borzunov/lib/python3.8/site-packages/hivemind/p2p/p2p_daemon_bindings/p2pclient.py", line 50, in close
        self.control.close()
    AttributeError: 'NoneType' object has no attribute 'close'
    ```

2. Makes bfloat16 serialization in hivemind.compression forward- and backward-compatible. The code before this PR **(a)** didn't work in torch < 1.13.0 (hivemind requires torch >= 1.9.0) and **(b)** led to this warnings on torch >= 2.0:

    ```python
    /opt/conda/lib/python3.10/site-packages/hivemind/compression/base.py:115: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
      tensor = torch.as_tensor(storage, dtype=torch.bfloat16)
    ```

    The new code works without warnings in all versions of PyTorch.

### CODE REVIEW

**Review by justheuristic — APPROVED** [review]
lgtm

File: hivemind/compression/base.py [hunk 1]
```diff
@@ -106,13 +105,13 @@ def extract(self, serialized_tensor: runtime_pb2.Tensor) -> torch.Tensor:
...
                 array = np.frombuffer(serialized_tensor.buffer, dtype=np.float32)
                 tensor = torch.as_tensor(array, dtype=torch.bfloat16)
-            else:  # efficient mode: send bfloat16 data directly
-                storage_type = torch.TypedStorage if hasattr(torch, "TypedStorage") else torch._TypedStorage
-                storage = storage_type.from_buffer(serialized_tensor.buffer, byte_order="little", dtype=torch.bfloat16)
-                tensor = torch.as_tensor(storage, dtype=torch.bfloat16)
+            else:
+                array = np.frombuffer(serialized_tensor.buffer, dtype=np.int16)
+                # reinterpret_cast from an arbitrary 2-byte type supported by numpy
+                tensor = torch.as_tensor(array).view(torch.bfloat16)
```
Comment (mryab) [inline hivemind/compression/base.py:114]: torch.as_tensor [takes the datatype](https://pytorch.org/docs/stable/generated/torch.as_tensor.html#torch.as_tensor) as one of the arguments, which means you can probably remove this view

File: hivemind/compression/base.py [hunk 2]
```diff
@@ -87,12 +87,11 @@ def compress(self, tensor: torch.Tensor, info: CompressionInfo, allow_inplace: b
...
-            if USE_LEGACY_BFLOAT16:
+            if USE_LEGACY_BFLOAT16:  # legacy mode: convert to fp32
                 raw_data = tensor.to(torch.float32)
-            else:
-                typed_storage = tensor.storage()
-                storage = typed_storage.untyped() if hasattr(typed_storage, "untyped") else typed_storage._untyped()
-                raw_data = torch.tensor(storage, dtype=torch.int8)
+            else:  # efficient mode: send bfloat16 data directly
+                # reinterpret_cast to an arbitrary 2-byte type supported by numpy
+                raw_data = tensor.view(torch.int16)
```
Comment (mryab) [inline hivemind/compression/base.py:94]: Sorry for a possibly stupid question, but would any 16-bit data type that's supported by numpy work here?

**Review by mryab — APPROVED** [review]
